version: "3"

networks:
  # определение сети с драйвером bridge
  polls_net:
    driver: bridge

services:
  # описание сервиса единой точки входа
  gateway:
    # докер образ, на основе котого создается контейнер
    image: nginx:latest
    # сети, в которых работает контейнер
    networks:
      - polls_net
    # соответствие портов хоста и контейнера
    ports:
      - "81:81"
    # соответствие директорий хоста и контейнера
    volumes:
      - ./config/nginx:/etc/nginx
      - ./logs/nginx:/var/log/nginx
      - ./placeholder/index.html:/var/www/placeholder/index.html

