version: "3"

networks:
  # внешняя сеть, определенная вне данного docker-compose.yml
  polls_net:
    external:
      name: gateway_polls_net

services:
  # описание сервиса auth_server
  auth_server:
    # имя контейнера
    container_name: auth_server
    # сети, в которых работает контейнер
    networks:
      - polls_net
    # расположение dockerfile для сборки контейнера
    build: .
    # соответствие портов хоста и контейнера
    ports:
      - "8081:8081"
    # контейнеры, от которых зависит данный
    depends_on:
      - pq_db
  pq_db:
    # сети, в которых работает контейнер
    networks:
      - polls_net
    # перезапустить контейнер, если он остановился
    restart: always
    # докер образ, на основе котого создается контейнер
    image: postgres:latest
    # соответствие директорий хоста и контейнера
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    # переменные окружения контейнера
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    # соответствие портов хоста и контейнера
    ports:
      - "5437:5432"
